export default {
  bg_color_black_80: { backgroundColor: 'var(--black_80)' },
  bg_color_black_90: { backgroundColor: 'var(--black_90)' },
  bg_color_black: { backgroundColor: 'var(--black)' },
  bg_color_error: { backgroundColor: 'var(--red)' },
  bg_color_info: { backgroundColor: 'var(--blue)' },
  bg_color_success: { backgroundColor: 'var(--green)' },
  bg_color_trans: { backgroundColor: 'transparent' },
  bg_color_warning: { backgroundColor: 'var(--yellow)' },
  bg_color_white_01: { backgroundColor: 'var(--white_01)' },
  bg_color_white_02: { backgroundColor: 'var(--white_02)' },
  bg_color_white_03: { backgroundColor: 'var(--white_03)' },
  bg_color_white_04: { backgroundColor: 'var(--white_04)' },
  bg_color_white_05: { backgroundColor: 'var(--white_05)' },
  bg_color_white_10: { backgroundColor: 'var(--white_10)' },
  bg_color_white_20: { backgroundColor: 'var(--white_20)' },
  bg_color_white_30: { backgroundColor: 'var(--white_30)' },
  bg_color_white_40: { backgroundColor: 'var(--white_40)' },
  bg_color_white_50: { backgroundColor: 'var(--white_50)' },
  bg_color_white_60: { backgroundColor: 'var(--white_60)' },
  bg_color_white_70: { backgroundColor: 'var(--white_70)' },
  bg_color_white: { backgroundColor: 'var(--white)' },
};
