export default {
  border_color_black_80: { borderColor: 'var(--black_80)' },
  border_color_black_90: { borderColor: 'var(--black_90)' },
  border_color_black: { borderColor: 'var(--black)' },
  border_color_white_01: { borderColor: 'var(--white_01)' },
  border_color_white_02: { borderColor: 'var(--white_02)' },
  border_color_white_03: { borderColor: 'var(--white_03)' },
  border_color_white_04: { borderColor: 'var(--white_04)' },
  border_color_white_05: { borderColor: 'var(--white_05)' },
  border_color_white_10: { borderColor: 'var(--white_10)' },
  border_color_white_20: { borderColor: 'var(--white_20)' },
  border_color_white_30: { borderColor: 'var(--white_30)' },
  border_color_white_40: { borderColor: 'var(--white_40)' },
  border_color_white_50: { borderColor: 'var(--white_50)' },
  border_color_white_60: { borderColor: 'var(--white_60)' },
  border_color_white_70: { borderColor: 'var(--white_70)' },
  border_color_white: { borderColor: 'var(--white)' },
  border_0: { border: 0 },
  border_style_solid: { borderStyle: 'solid' },
  border_width_1: { borderWidth: 1 },
};
