export default {
  color_black_80: { color: 'var(--black_80)' },
  color_black_90: { color: 'var(--black_90)' },
  color_black: { color: 'var(--black)' },
  color_error: { color: 'var(--red)' },
  color_info: { color: 'var(--blue)' },
  color_success: { color: 'var(--green)' },
  color_warning: { color: 'var(--yellow)' },
  color_white_01: { color: 'var(--white_01)' },
  color_white_02: { color: 'var(--white_02)' },
  color_white_03: { color: 'var(--white_03)' },
  color_white_04: { color: 'var(--white_04)' },
  color_white_05: { color: 'var(--white_05)' },
  color_white_10: { color: 'var(--white_10)' },
  color_white_20: { color: 'var(--white_20)' },
  color_white_30: { color: 'var(--white_30)' },
  color_white_40: { color: 'var(--white_40)' },
  color_white_50: { color: 'var(--white_50)' },
  color_white_60: { color: 'var(--white_60)' },
  color_white_70: { color: 'var(--white_70)' },
  color_white: { color: 'var(--white)' },
};
