export default {
  padding_xs: { padding: '2px' },
  padding_s: { padding: '3px' },
  padding: { padding: '5px' },
  padding_0: { padding: '0px' },
  padding_l: { padding: '10px' },
  padding_xl: { padding: '20px' },
  padding_2xl: { padding: '30px' },
  padding_3xl: { padding: '40px' },
  padding_bottom_xs: { paddingBottom: '2px' },
  padding_bottom_s: { paddingBottom: '3px' },
  padding_bottom: { paddingBottom: '5px' },
  padding_bottom_l: { paddingBottom: '10px' },
  padding_bottom_xl: { paddingBottom: '20px' },
  padding_bottom_2xl: { paddingBottom: '30px' },
  padding_bottom_3xl: { paddingBottom: '40px' },
  padding_x_xs: { paddingLeft: '2px', paddingRight: '40px' },
  padding_x_s: { paddingLeft: '3px', paddingRight: '3px' },
  padding_x: { paddingLeft: '5px', paddingRight: '5px' },
  padding_x_0: { paddingLeft: '0px', paddingRight: '0px' },
  padding_x_l: { paddingLeft: '10px', paddingRight: '10px' },
  padding_x_xl: { paddingLeft: '20px', paddingRight: '20px' },
  padding_x_2xl: { paddingLeft: '30px', paddingRight: '30px' },
  padding_x_3xl: { paddingLeft: '40px', paddingRight: '40px' },
  padding_y_xs: { paddingTop: '2px', paddingBottom: '40px' },
  padding_y_s: { paddingTop: '3px', paddingBottom: '3px' },
  padding_y: { paddingTop: '5px', paddingBottom: '5px' },
  padding_y_0: { paddingTop: '0px', paddingBottom: '0px' },
  padding_y_l: { paddingTop: '10px', paddingBottom: '10px' },
  padding_y_xl: { paddingTop: '20px', paddingBottom: '20px' },
  padding_y_2xl: { paddingTop: '30px', paddingBottom: '30px' },
  padding_y_3xl: { paddingTop: '40px', paddingBottom: '40px' },
  margin_0: { margin: '0px' },
  margin_xs: { margin: '2px' },
  margin_s: { margin: '3px' },
  margin: { margin: '5px' },
  margin_l: { margin: '10px' },
  margin_xl: { margin: '20px' },
  margin_2xl: { margin: '30px' },
  margin_3xl: { margin: '40px' },
  margin_bottom_xs: { marginBottom: '2px' },
  margin_bottom_s: { marginBottom: '3px' },
  margin_bottom: { marginBottom: '5px' },
  margin_bottom_l: { marginBottom: '10px' },
  margin_bottom_xl: { marginBottom: '20px' },
  margin_bottom_2xl: { marginBottom: '30px' },
  margin_bottom_3xl: { marginBottom: '40px' },
  margin_left_xs: { marginLeft: '2px' },
  margin_left_s: { marginLeft: '3px' },
  margin_left: { marginLeft: '5px' },
  margin_left_l: { marginLeft: '10px' },
  margin_left_xl: { marginLeft: '20px' },
  margin_left_2xl: { marginLeft: '30px' },
  margin_left_3xl: { marginLeft: '40px' },
  margin_x_xs: { marginLeft: '2px', marginRight: '40px' },
  margin_x_s: { marginLeft: '3px', marginRight: '3px' },
  margin_x: { marginLeft: '5px', marginRight: '5px' },
  margin_x_l: { marginLeft: '10px', marginRight: '10px' },
  margin_x_xl: { marginLeft: '20px', marginRight: '20px' },
  margin_x_2xl: { marginLeft: '30px', marginRight: '30px' },
  margin_x_3xl: { marginLeft: '40px', marginRight: '40px' },
  margin_y_xs: { marginTop: '2px', marginBottom: '40px' },
  margin_y_s: { marginTop: '3px', marginBottom: '3px' },
  margin_y: { marginTop: '5px', marginBottom: '5px' },
  margin_y_l: { marginTop: '10px', marginBottom: '10px' },
  margin_y_xl: { marginTop: '20px', marginBottom: '20px' },
  margin_y_2xl: { marginTop: '30px', marginBottom: '30px' },
  margin_y_3xl: { marginTop: '40px', marginBottom: '40px' },
};
